# Generated by Django 3.1.3 on 2021-01-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travelling', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='city',
        ),
    ]
