# Generated by Django 3.1.3 on 2021-01-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travelling', '0002_delete_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table='data',
        ),
    ]
