# Generated by Django 3.1.3 on 2021-01-06 06:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Travelling', '0003_auto_20210104_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nopass', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
