# Generated by Django 3.1.3 on 2021-01-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelling', '0007_auto_20210106_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerdata',
            name='busid',
            field=models.IntegerField(null=True),
        ),
    ]
