# Generated by Django 3.1.3 on 2021-01-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelling', '0008_passengerdata_busid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerdata',
            name='bustype',
            field=models.CharField(choices=[('Pallevellugu', 'Pallevellugu'), ('Express', 'Express'), ('Ultra Deluxe', 'Ultra Deluxe')], max_length=30, null=True),
        ),
    ]
